const inventoryData = [
  {
    id: 1,
    image: "🥛",
    name: "Raw Sugar",
    sku: "RS-1001",
    category: "Raw Materials",
    stock: 120,
    unit: "kg",
    reorder: 250,
    status: "Low Stock",
  },
  {
    id: 2,
    image: "🥛",
    name: "Milk Powder",
    sku: "MP-1002",
    category: "Raw Materials",
    stock: 80,
    unit: "kg",
    reorder: 200,
    status: "Low Stock",
  },
  {
    id: 3,
    image: "🍫",
    name: "Chocolate Syrup",
    sku: "CS-1003",
    category: "Raw Materials",
    stock: 25,
    unit: "L",
    reorder: 100,
    status: "Critical",
  },
  {
    id: 4,
    image: "📦",
    name: "Packaging Box",
    sku: "PB-1004",
    category: "Packaging",
    stock: 150,
    unit: "pcs",
    reorder: 300,
    status: "Low Stock",
  },
  {
    id: 5,
    image: "🍦",
    name: "Ice Cream Cup",
    sku: "IC-1006",
    category: "Packaging",
    stock: 2500,
    unit: "pcs",
    reorder: 1000,
    status: "In Stock",
  },
];

export default inventoryData;