export const productionOrders = [
  {
    id: "PRD-1001",
    product: "Chocolate Ice Cream",
    batch: "BCH-2101",
    quantity: 500,
    machine: "Mixer A",
    supervisor: "John David",
    startDate: "20 Jul 2026",
    dueDate: "25 Jul 2026",
    progress: 85,
    status: "In Progress",
  },
  {
    id: "PRD-1002",
    product: "Vanilla Ice Cream",
    batch: "BCH-2102",
    quantity: 350,
    machine: "Mixer B",
    supervisor: "Sarah Wilson",
    startDate: "18 Jul 2026",
    dueDate: "22 Jul 2026",
    progress: 100,
    status: "Completed",
  },
  {
    id: "PRD-1003",
    product: "Strawberry Milkshake",
    batch: "BCH-2103",
    quantity: 200,
    machine: "Blender A",
    supervisor: "Michael",
    startDate: "21 Jul 2026",
    dueDate: "26 Jul 2026",
    progress: 45,
    status: "In Progress",
  },
  {
    id: "PRD-1004",
    product: "Chocolate Bar",
    batch: "BCH-2104",
    quantity: 1200,
    machine: "Packing Line",
    supervisor: "Emma",
    startDate: "22 Jul 2026",
    dueDate: "27 Jul 2026",
    progress: 15,
    status: "Pending",
  },
  {
    id: "PRD-1005",
    product: "Butter Scotch Cone",
    batch: "BCH-2105",
    quantity: 700,
    machine: "Cone Line",
    supervisor: "David",
    startDate: "17 Jul 2026",
    dueDate: "21 Jul 2026",
    progress: 100,
    status: "Completed",
  },
];
