export const purchaseOrders = [
  {
    id: "PO-1001",
    supplier: "ABC Foods Pvt Ltd",
    warehouse: "Main Warehouse",
    date: "24 Jul 2026",
    items: 12,
    amount: "₹24,500",
    status: "Pending",
    payment: "Unpaid",
  },
  {
    id: "PO-1002",
    supplier: "Fresh Dairy",
    warehouse: "North Warehouse",
    date: "25 Jul 2026",
    items: 8,
    amount: "₹18,200",
    status: "Received",
    payment: "Paid",
  },
  {
    id: "PO-1003",
    supplier: "Metro Packaging",
    warehouse: "Main Warehouse",
    date: "26 Jul 2026",
    items: 20,
    amount: "₹52,900",
    status: "Ordered",
    payment: "Partial",
  },
  {
    id: "PO-1004",
    supplier: "Premium Chemicals",
    warehouse: "Factory Store",
    date: "27 Jul 2026",
    items: 6,
    amount: "₹11,800",
    status: "Pending",
    payment: "Unpaid",
  },
  {
    id: "PO-1005",
    supplier: "Global Traders",
    warehouse: "Central Warehouse",
    date: "28 Jul 2026",
    items: 15,
    amount: "₹34,650",
    status: "Cancelled",
    payment: "Unpaid",
  },
];