export const suppliers = [
  {
    id: 1,
    avatar: "AF",
    avatarColor: "bg-emerald-500",
    company: "ABC Foods Pvt Ltd",
    gstin: "27ABCDE1234F1Z5",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Sugar",
      "Milk Powder",
      "Cocoa Powder",
    ],
    contact: "John Mathew",
    phone: "+91 98765 43210",
    email: "john@abcfoods.com",
    outstanding: 85400,
    outstandingType: "Payable",
    orders: 42,
  },

  {
    id: 2,
    avatar: "PP",
    avatarColor: "bg-violet-500",
    company: "PackPro Solutions",
    gstin: "32XYZAB5678C1Z2",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Carton Boxes",
      "Packaging Materials",
    ],
    contact: "Anita Sharma",
    phone: "+91 91234 56789",
    email: "anita@packpro.com",
    outstanding: 0,
    outstandingType: "Settled",
    orders: 18,
  },

  {
    id: 3,
    avatar: "KM",
    avatarColor: "bg-blue-500",
    company: "Kerala Milk Suppliers",
    gstin: "32KLMNO1234D1Z3",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Milk Powder",
      "Butter",
      "Cheese",
    ],
    contact: "Rahim P.",
    phone: "+91 87654 32109",
    email: "rahim@kms.com",
    outstanding: 124500,
    outstandingType: "Payable",
    orders: 31,
  },

  {
    id: 4,
    avatar: "SP",
    avatarColor: "bg-orange-500",
    company: "Sweet Plus Ingredients",
    gstin: "29SWEET1234E1Z4",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Flavors",
      "Essence",
      "Additives",
    ],
    contact: "Suresh N.",
    phone: "+91 93456 78901",
    email: "suresh@sweetplus.com",
    outstanding: 36750,
    outstandingType: "Payable",
    orders: 16,
  },

  {
    id: 5,
    avatar: "XL",
    avatarColor: "bg-cyan-500",
    company: "XL Packaging",
    gstin: "32XLPAK9876F1Z5",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "HDPE Buckets",
      "Containers",
      "Lids",
    ],
    contact: "Vikram Singh",
    phone: "+91 99887 76655",
    email: "vikram@xlpack.com",
    outstanding: 54300,
    outstandingType: "Payable",
    orders: 14,
  },

  {
    id: 6,
    avatar: "RT",
    avatarColor: "bg-emerald-600",
    company: "Retail Mart",
    gstin: "29RETAIL4455G1Z6",
    partyType: "Sundry Debtor",
    supplyCategory: [
      "Finished Products",
      "Ice Cream",
    ],
    contact: "Neeraj Menon",
    phone: "+91 98899 44556",
    email: "neeraj@retailmart.com",
    outstanding: 248600,
    outstandingType: "Receivable",
    orders: 28,
  },
];