export const suppliers = [
  {
    id: 1,
    avatar: "AF",
    avatarColor: "bg-emerald-500",
    company: "ABC Foods Pvt Ltd",
    gstin: "27ABCDE1234F1Z5",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Sugar",
      "Milk Powder",
      "Cocoa Powder",
    ],
    contact: "John Mathew",
    phone: "+91 98765 43210",
    email: "john@abcfoods.com",
    outstanding: 85400,
    outstandingType: "Payable",
    orders: 42,
  },

  {
    id: 2,
    avatar: "PP",
    avatarColor: "bg-violet-500",
    company: "PackPro Solutions",
    gstin: "32XYZAB5678C1Z2",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Carton Boxes",
      "Packaging Materials",
    ],
    contact: "Anita Sharma",
    phone: "+91 91234 56789",
    email: "anita@packpro.com",
    outstanding: 0,
    outstandingType: "Settled",
    orders: 18,
  },

  {
    id: 3,
    avatar: "KM",
    avatarColor: "bg-blue-500",
    company: "Kerala Milk Suppliers",
    gstin: "32KLMNO1234D1Z3",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Milk Powder",
      "Butter",
      "Cheese",
    ],
    contact: "Rahim P.",
    phone: "+91 87654 32109",
    email: "rahim@kms.com",
    outstanding: 124500,
    outstandingType: "Payable",
    orders: 31,
  },

  {
    id: 4,
    avatar: "SP",
    avatarColor: "bg-orange-500",
    company: "Sweet Plus Ingredients",
    gstin: "29SWEET1234E1Z4",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Flavors",
      "Essence",
      "Additives",
    ],
    contact: "Suresh N.",
    phone: "+91 93456 78901",
    email: "suresh@sweetplus.com",
    outstanding: 36750,
    outstandingType: "Payable",
    orders: 16,
  },

  {
    id: 5,
    avatar: "XL",
    avatarColor: "bg-cyan-500",
    company: "XL Packaging",
    gstin: "32XLPAK9876F1Z5",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "HDPE Buckets",
      "Containers",
      "Lids",
    ],
    contact: "Vikram Singh",
    phone: "+91 99887 76655",
    email: "vikram@xlpack.com",
    outstanding: 54300,
    outstandingType: "Payable",
    orders: 14,
  },

  {
    id: 6,
    avatar: "RT",
    avatarColor: "bg-emerald-600",
    company: "Retail Mart",
    gstin: "29RETAIL4455G1Z6",
    partyType: "Sundry Debtor",
    supplyCategory: [
      "Finished Products",
      "Ice Cream",
    ],
    contact: "Neeraj Menon",
    phone: "+91 98899 44556",
    email: "neeraj@retailmart.com",
    outstanding: 248600,
    outstandingType: "Receivable",
    orders: 28,
  },

  {
    id: 7,
    avatar: "FD",
    avatarColor: "bg-purple-500",
    company: "Fresh Dairy Stores",
    gstin: "32FRESH1122H1Z7",
    partyType: "Sundry Debtor",
    supplyCategory: [
      "Ice Cream",
      "Milk Shake Mix",
    ],
    contact: "Deepak Nair",
    phone: "+91 90678 11223",
    email: "deepak@freshdairy.com",
    outstanding: 102400,
    outstandingType: "Receivable",
    orders: 17,
  },

  {
    id: 8,
    avatar: "OT",
    avatarColor: "bg-slate-500",
    company: "Oceanic Transports",
    gstin: "32OCEAN7788I1Z8",
    partyType: "Other Party",
    supplyCategory: [
      "Transportation",
      "Services",
    ],
    contact: "Arun Jose",
    phone: "+91 80890 33445",
    email: "arun@oceanic.com",
    outstanding: 0,
    outstandingType: "Settled",
    orders: 9,
  },

  {
    id: 9,
    avatar: "SM",
    avatarColor: "bg-amber-700",
    company: "Suresh Metals",
    gstin: "29SURESH2233J1Z9",
    partyType: "Sundry Creditor",
    supplyCategory: [
      "Stainless Steel",
      "Accessories",
    ],
    contact: "Suresh Babu",
    phone: "+91 93490 22334",
    email: "sales@sureshmetals.com",
    outstanding: 12400,
    outstandingType: "Payable",
    orders: 6,
  },

  {
    id: 10,
    avatar: "GL",
    avatarColor: "bg-pink-500",
    company: "Global Traders",
    gstin: "07GLOBAL3344K1Z0",
    partyType: "Other Party",
    supplyCategory: [
      "Not Specified",
    ],
    contact: "Global Support",
    phone: "+91 88777 66554",
    email: "support@global.com",
    outstanding: 0,
    outstandingType: "Settled",
    orders: 2,
  },
];