export const reports = [
  {
    id: 1,
    name: "Inventory Summary",
    category: "Inventory",
    type: "Summary",
    generated: "Today, 10:30 AM",
    period: "Jul 1 - Jul 31",
    format: ["CSV", "Excel"],
  },
  {
    id: 2,
    name: "Purchase Analysis",
    category: "Purchases",
    type: "Analytics",
    generated: "Yesterday",
    period: "Q2 2026",
    format: ["CSV", "Excel"],
  },
  {
    id: 3,
    name: "Production Efficiency",
    category: "Production",
    type: "Detailed",
    generated: "22 Jul 2026",
    period: "Monthly",
    format: ["CSV", "Excel"],
  },
  {
    id: 4,
    name: "Sales Overview",
    category: "Sales",
    type: "Summary",
    generated: "20 Jul 2026",
    period: "Quarterly",
    format: ["CSV", "Excel"],
  },
  {
    id: 5,
    name: "Financial Statement",
    category: "Finance",
    type: "Detailed",
    generated: "18 Jul 2026",
    period: "Yearly",
    format: ["CSV", "Excel"],
  },
];